server:
  port: ${PORT:8081}

api:
  endpoint:
    deposit: https://beertech-bank.herokuapp.com/transactions/accountCode/deposit
    withdrawal: https://beertech-bank.herokuapp.com/transactions/accountCode/withdrawal
    transfer: https://beertech-bank.herokuapp.com/transactions/accountCode/transfer
    statements: https://beertech-bank.herokuapp.com/transactions/accountCode/statements



spring:
  rabbitmq:

    addresses: ${CLOUDAMQP_URL}

    exchange: transactions.consumer.exchange

    queue:
      deposit: deposit.queue
      withdrawal: withdrawal.queue
      transfer: transfer.queue
      statements: statements.queue

    routingkey:
      deposit: deposit.rk
      withdrawal: withdrawal.rk
      transfer: transfer.rk
      statements: statements.rk