server:
  port: 8080

spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace
    hibernate:
      ddl-auto: update

    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password

  rabbitmq:
    exchange: payment.externalbank.exchange

    queue:
      payment: payment.queue

    routingkey:
      payment: payment.rk

beertech:
  swagger:
    baseUrl: ${SWAGGER_BASE_URL:localhost:${server.port}}
    apiInfo: REST API for Bank Becks Service Microservice
    apiTitle: BeerTech Bank Becks Service


security:
  jwt:
    expiry: 3000
    key: abcde