server:
  port: 8082

api:
  endpoint:
    payment: http://localhost:8080/payment-slips/code

spring:
  rabbitmq:
    exchange: payment.externalbank.exchange

    queue:
      payment: payment.queue

    routingkey:
      payment: payment.rk