server:
  port: 8082


spring:
  rabbitmq:
    exchange: payment.externalbank.exchange

    queue:
      payment: payment.queue

    routingkey:
      payment: payment.rk

api:
  endpoint:
    create-payment-slip: https://localhost:8080/transactions/accountCode/deposit